name: Solidity contract tests
on: [push, pull_request]
jobs:
  tests:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: node version
        run: node --version

      - name: contract - install dependencies
        run: yarn
        working-directory: ./contract

      - name: install dependencies needed for utils module
        run: yarn
        working-directory: ./web-server

      - name: contract - test
        run: yarn test-ci
        working-directory: ./contract

  styling:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: tests
    steps:
    - uses: actions/checkout@v2

    # run prettier, and also ensure any lock file changes are reverted
    - name: Prettify web-client
      run: yarn && yarn style
      working-directory: ./web-client

    # run prettier, and also ensure any lock file changes are reverted
    - name: Prettify web-server
      run: yarn && yarn style
      working-directory: ./web-server

    # run prettier, and also ensure any lock file changes are reverted
    - name: Prettify contract
      run: yarn && yarn style
      working-directory: ./contract

    # commit and push changes
    - name: Commit style fixes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Code style fixes
        commit_user_name: Github Action
